INFO     mylog:conftest.py:74 ====学生身份进行登录====
INFO     mylog:base_page.py:119 往输入框--【登录页面_账号输入】--输入值成功
INFO     mylog:base_page.py:119 往输入框--【登录页面_密码输入】--输入值成功
INFO     mylog:base_page.py:101 点击元素--【登录页面_登录按钮】--成功
INFO     mylog:base_page.py:101 点击元素--【首页_学生加入课程】--成功
INFO     mylog:base_page.py:119 往输入框--【首页_学生输入加课码】--输入值成功
INFO     mylog:base_page.py:101 点击元素--【首页_学生加入课程的加入按钮】--成功
INFO     mylog:base_page.py:192 等待元素可见--【首页_加课失败的错误提示】--成功
INFO     mylog:test_join_the_course.py:98 ————>执行通过
WARNING  urllib3.connectionpool:connectionpool.py:662 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0D4CA2B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/882a2c07ead5696e9a0a8114c0788d80
WARNING  urllib3.connectionpool:connectionpool.py:662 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0D4CA0B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/882a2c07ead5696e9a0a8114c0788d80
WARNING  urllib3.connectionpool:connectionpool.py:662 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0D4CA990>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/882a2c07ead5696e9a0a8114c0788d80