{"name": "账号错误", "status": "passed", "parameters": [{"name": "case", "value": "{'data': 14, 'title': '账号错误'}"}], "start": 1614260767623, "stop": 1614260767623, "uuid": "c1f873ce-1328-4934-bcec-33d17059392b", "historyId": "d2bfeb3e948a592e21c898c84d0fd65d", "testCaseId": "23d1d12ac7f8bc2e08d2f18b0fee7c59", "fullName": "testcases.test_login.TestLogin#test_login_error", "labels": [{"name": "story", "value": "登录功能"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MuSen"}, {"name": "thread", "value": "8296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}