{"name": "账号错误", "status": "passed", "parameters": [{"name": "case", "value": "{'data': 14, 'title': '账号错误'}"}], "start": 1614260860067, "stop": 1614260860067, "uuid": "4920e1b6-6c78-48b7-b75c-0123c1d9d046", "historyId": "d2bfeb3e948a592e21c898c84d0fd65d", "testCaseId": "23d1d12ac7f8bc2e08d2f18b0fee7c59", "fullName": "testcases.test_login.TestLogin#test_login_error", "labels": [{"name": "suite", "value": "用户模块"}, {"name": "story", "value": "登录功能"}, {"name": "parentSuite", "value": "testcases"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MuSen"}, {"name": "thread", "value": "3856-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}