{"name": "test_demo888[2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 > 20", "trace": "self = <test_demo3.TestDome999 object at 0x0E947E90>, item = 2\n\n    @pytest.mark.parametrize('item', cases)\n    def test_demo888(self, item):\n>       assert item > 20\nE       assert 2 > 20\n\ntestcase\\test_demo3.py:27: AssertionError"}, "parameters": [{"name": "item", "value": "2"}], "start": 1610767573729, "stop": 1610767573730, "uuid": "2beb407f-fc39-41b8-bbac-511e51a7be57", "historyId": "423f70255d23d17705bd48c603ecd831", "testCaseId": "1650fc4990c3977bfa462cebf092ff59", "fullName": "testcase.test_demo3.TestDome999#test_demo888", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_demo3"}, {"name": "subSuite", "value": "TestDome999"}, {"name": "host", "value": "MuSen"}, {"name": "thread", "value": "6004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_demo3"}]}