{"name": "test_demo888[4]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 > 20", "trace": "self = <test_demo3.TestDome999 object at 0x0E93E9B0>, item = 4\n\n    @pytest.mark.parametrize('item', cases)\n    def test_demo888(self, item):\n>       assert item > 20\nE       assert 4 > 20\n\ntestcase\\test_demo3.py:27: AssertionError"}, "parameters": [{"name": "item", "value": "4"}], "start": 1610767563685, "stop": 1610767563685, "uuid": "eb38e7c3-d70b-4635-858c-8fcfb67b99e1", "historyId": "777742ad1325f67e0cd5e121d7ef0d53", "testCaseId": "1650fc4990c3977bfa462cebf092ff59", "fullName": "testcase.test_demo3.TestDome999#test_demo888", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_demo3"}, {"name": "subSuite", "value": "TestDome999"}, {"name": "host", "value": "MuSen"}, {"name": "thread", "value": "6004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_demo3"}]}