2020-12-19 10:55:52,303 - [test_register.py-->line:52] - INFO: 用例--【注册成功-带注册名】---执行通过
2020-12-19 10:55:52,586 - [test_register.py-->line:52] - INFO: 用例--【成功-不带用户名】---执行通过
2020-12-19 10:55:52,657 - [test_register.py-->line:52] - INFO: 用例--【不输入手机号】---执行通过
2020-12-19 10:55:52,718 - [test_register.py-->line:52] - INFO: 用例--【手机号长度10位】---执行通过
2020-12-19 10:55:52,774 - [test_register.py-->line:52] - INFO: 用例--【手机号长度12位】---执行通过
2020-12-19 10:55:52,822 - [test_register.py-->line:52] - INFO: 用例--【手机号含有非法字符】---执行通过
2020-12-19 10:55:53,073 - [test_register.py-->line:52] - INFO: 用例--【已注册过的手机号】---执行通过
2020-12-19 10:55:53,151 - [test_register.py-->line:52] - INFO: 用例--【密码7位】---执行通过
2020-12-19 10:55:53,192 - [test_register.py-->line:52] - INFO: 用例--【密码17位】---执行通过
2020-12-19 10:55:53,246 - [test_register.py-->line:52] - INFO: 用例--【不输入密码】---执行通过
2020-12-19 10:55:53,447 - [test_register.py-->line:47] - ERROR: 用例--【注册名11位】---执行失败
2020-12-19 10:55:53,447 - [test_register.py-->line:48] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\project\python_35\py35_21day_project\testcases\test_register.py", line 43, in test_register
    self.assertEqual(expected['code'], res['code'])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2020-12-19 10:55:53,490 - [test_register.py-->line:52] - INFO: 用例--【类型输入非0，1内容】---执行通过
2020-12-19 10:55:53,744 - [test_register.py-->line:47] - ERROR: 用例--【不输入类型】---执行失败
2020-12-19 10:55:53,745 - [test_register.py-->line:48] - ERROR: '用户类型为空' != 'OK'
- 用户类型为空
+ OK
Traceback (most recent call last):
  File "C:\project\python_35\py35_21day_project\testcases\test_register.py", line 44, in test_register
    self.assertEqual(expected['msg'], res['msg'])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '用户类型为空' != 'OK'
- 用户类型为空
+ OK

2020-12-19 10:59:55,019 - [test_register.py-->line:52] - INFO: 用例--【注册成功-带注册名】---执行通过
2020-12-19 10:59:55,297 - [test_register.py-->line:52] - INFO: 用例--【成功-不带用户名】---执行通过
2020-12-19 10:59:55,353 - [test_register.py-->line:52] - INFO: 用例--【不输入手机号】---执行通过
2020-12-19 10:59:55,439 - [test_register.py-->line:52] - INFO: 用例--【手机号长度10位】---执行通过
2020-12-19 10:59:55,501 - [test_register.py-->line:52] - INFO: 用例--【手机号长度12位】---执行通过
2020-12-19 10:59:55,543 - [test_register.py-->line:52] - INFO: 用例--【手机号含有非法字符】---执行通过
2020-12-19 10:59:55,821 - [test_register.py-->line:52] - INFO: 用例--【已注册过的手机号】---执行通过
2020-12-19 10:59:55,891 - [test_register.py-->line:52] - INFO: 用例--【密码7位】---执行通过
2020-12-19 10:59:55,958 - [test_register.py-->line:52] - INFO: 用例--【密码17位】---执行通过
2020-12-19 10:59:56,016 - [test_register.py-->line:52] - INFO: 用例--【不输入密码】---执行通过
2020-12-19 10:59:56,063 - [test_register.py-->line:52] - INFO: 用例--【注册名11位】---执行通过
2020-12-19 10:59:56,134 - [test_register.py-->line:52] - INFO: 用例--【类型输入非0，1内容】---执行通过
2020-12-19 10:59:56,407 - [test_register.py-->line:52] - INFO: 用例--【不输入类型】---执行通过
2020-12-19 11:08:07,974 - [test_login.py-->line:52] - INFO: 用例--【登录成功】---执行通过
2020-12-19 11:08:08,019 - [test_login.py-->line:52] - INFO: 用例--【手机号为空】---执行通过
2020-12-19 11:08:08,078 - [test_login.py-->line:52] - INFO: 用例--【密码为空】---执行通过
2020-12-19 11:08:08,348 - [test_login.py-->line:52] - INFO: 用例--【手机号未注册】---执行通过
2020-12-19 11:08:08,620 - [test_login.py-->line:52] - INFO: 用例--【密码错误】---执行通过
2020-12-19 11:08:08,675 - [test_login.py-->line:52] - INFO: 用例--【手机号格式错误】---执行通过
2020-12-19 11:08:08,938 - [test_register.py-->line:47] - ERROR: 用例--【注册成功-带注册名】---执行失败
2020-12-19 11:08:08,938 - [test_register.py-->line:48] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\project\python_35\py35_21day_project\testcases\test_register.py", line 43, in test_register
    self.assertEqual(expected['code'], res['code'])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-12-19 11:08:09,201 - [test_register.py-->line:47] - ERROR: 用例--【成功-不带用户名】---执行失败
2020-12-19 11:08:09,201 - [test_register.py-->line:48] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\project\python_35\py35_21day_project\testcases\test_register.py", line 43, in test_register
    self.assertEqual(expected['code'], res['code'])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-12-19 11:08:09,262 - [test_register.py-->line:52] - INFO: 用例--【不输入手机号】---执行通过
2020-12-19 11:08:09,336 - [test_register.py-->line:52] - INFO: 用例--【手机号长度10位】---执行通过
2020-12-19 11:08:09,394 - [test_register.py-->line:52] - INFO: 用例--【手机号长度12位】---执行通过
2020-12-19 11:08:09,459 - [test_register.py-->line:52] - INFO: 用例--【手机号含有非法字符】---执行通过
2020-12-19 11:08:09,751 - [test_register.py-->line:52] - INFO: 用例--【已注册过的手机号】---执行通过
2020-12-19 11:08:09,810 - [test_register.py-->line:52] - INFO: 用例--【密码7位】---执行通过
2020-12-19 11:08:09,866 - [test_register.py-->line:52] - INFO: 用例--【密码17位】---执行通过
2020-12-19 11:08:09,931 - [test_register.py-->line:52] - INFO: 用例--【不输入密码】---执行通过
2020-12-19 11:08:10,009 - [test_register.py-->line:52] - INFO: 用例--【注册名11位】---执行通过
2020-12-19 11:08:10,088 - [test_register.py-->line:52] - INFO: 用例--【类型输入非0，1内容】---执行通过
2020-12-19 11:08:10,358 - [test_register.py-->line:47] - ERROR: 用例--【不输入类型】---执行失败
2020-12-19 11:08:10,358 - [test_register.py-->line:48] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\project\python_35\py35_21day_project\testcases\test_register.py", line 43, in test_register
    self.assertEqual(expected['code'], res['code'])
  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-12-19 11:44:31,960 - [test_login.py-->line:47] - ERROR: 用例--【登录成功】---执行失败
2020-12-19 11:44:31,961 - [test_login.py-->line:48] - ERROR: {'code': 0, 'msg': 'OK'} not in {'code': 0, 'msg': 'OK', 'data': {'id': 59473, 'leave_amount': 40000.0, 'mobile_phone': '13367822221', 'reg_name': '小柠檬666', 'reg_time': '2020-11-16 21:24:27.0', 'type': 1, 'token_info': {'token_type': 'Bearer', 'expires_in': '2020-12-19 11:49:31', 'token': 'eyJhbGciOiJIUzUxMiJ9.eyJtZW1iZXJfaWQiOjU5NDczLCJleHAiOjE2MDgzNDk3NzF9.m_VcGuWasQppyPhfMXiAZyZYpv4PFjfScoZUa4GSxkvuzF16-1hlc_9d8W9FtBayMFLs4XNOqBheRgWUkGTKAA'}}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
Traceback (most recent call last):
  File "C:\project\python_35\py35_21day_project\testcases\test_login.py", line 44, in test_login
    self.assertDictIn(expected,res)
  File "C:\project\python_35\py35_21day_project\testcases\test_login.py", line 60, in assertDictIn
    raise AssertionError("{} not in {}".format(expected, res))
AssertionError: {'code': 0, 'msg': 'OK'} not in {'code': 0, 'msg': 'OK', 'data': {'id': 59473, 'leave_amount': 40000.0, 'mobile_phone': '13367822221', 'reg_name': '小柠檬666', 'reg_time': '2020-11-16 21:24:27.0', 'type': 1, 'token_info': {'token_type': 'Bearer', 'expires_in': '2020-12-19 11:49:31', 'token': 'eyJhbGciOiJIUzUxMiJ9.eyJtZW1iZXJfaWQiOjU5NDczLCJleHAiOjE2MDgzNDk3NzF9.m_VcGuWasQppyPhfMXiAZyZYpv4PFjfScoZUa4GSxkvuzF16-1hlc_9d8W9FtBayMFLs4XNOqBheRgWUkGTKAA'}}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2020-12-19 11:44:32,043 - [test_login.py-->line:47] - ERROR: 用例--【手机号为空】---执行失败
2020-12-19 11:44:32,043 - [test_login.py-->line:48] - ERROR: {'code': 1, 'msg': '手机号码为空'} not in {'code': 1, 'msg': '手机号码为空', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
Traceback (most recent call last):
  File "C:\project\python_35\py35_21day_project\testcases\test_login.py", line 44, in test_login
    self.assertDictIn(expected,res)
  File "C:\project\python_35\py35_21day_project\testcases\test_login.py", line 60, in assertDictIn
    raise AssertionError("{} not in {}".format(expected, res))
AssertionError: {'code': 1, 'msg': '手机号码为空'} not in {'code': 1, 'msg': '手机号码为空', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2020-12-19 11:44:32,115 - [test_login.py-->line:47] - ERROR: 用例--【密码为空】---执行失败
2020-12-19 11:44:32,115 - [test_login.py-->line:48] - ERROR: {'code': 1, 'msg': '密码为空'} not in {'code': 1, 'msg': '密码为空', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
Traceback (most recent call last):
  File "C:\project\python_35\py35_21day_project\testcases\test_login.py", line 44, in test_login
    self.assertDictIn(expected,res)
  File "C:\project\python_35\py35_21day_project\testcases\test_login.py", line 60, in assertDictIn
    raise AssertionError("{} not in {}".format(expected, res))
AssertionError: {'code': 1, 'msg': '密码为空'} not in {'code': 1, 'msg': '密码为空', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2020-12-19 11:44:32,391 - [test_login.py-->line:47] - ERROR: 用例--【手机号未注册】---执行失败
2020-12-19 11:44:32,392 - [test_login.py-->line:48] - ERROR: {'code': 1001, 'msg': '账号信息错误'} not in {'code': 1001, 'msg': '账号信息错误', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
Traceback (most recent call last):
  File "C:\project\python_35\py35_21day_project\testcases\test_login.py", line 44, in test_login
    self.assertDictIn(expected,res)
  File "C:\project\python_35\py35_21day_project\testcases\test_login.py", line 60, in assertDictIn
    raise AssertionError("{} not in {}".format(expected, res))
AssertionError: {'code': 1001, 'msg': '账号信息错误'} not in {'code': 1001, 'msg': '账号信息错误', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2020-12-19 11:44:32,672 - [test_login.py-->line:47] - ERROR: 用例--【密码错误】---执行失败
2020-12-19 11:44:32,672 - [test_login.py-->line:48] - ERROR: {'code': 1001, 'msg': '账号信息错误'} not in {'code': 1001, 'msg': '账号信息错误', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
Traceback (most recent call last):
  File "C:\project\python_35\py35_21day_project\testcases\test_login.py", line 44, in test_login
    self.assertDictIn(expected,res)
  File "C:\project\python_35\py35_21day_project\testcases\test_login.py", line 60, in assertDictIn
    raise AssertionError("{} not in {}".format(expected, res))
AssertionError: {'code': 1001, 'msg': '账号信息错误'} not in {'code': 1001, 'msg': '账号信息错误', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2020-12-19 11:44:32,744 - [test_login.py-->line:47] - ERROR: 用例--【手机号格式错误】---执行失败
2020-12-19 11:44:32,744 - [test_login.py-->line:48] - ERROR: {'code': 2, 'msg': '无效的手机格式'} not in {'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
Traceback (most recent call last):
  File "C:\project\python_35\py35_21day_project\testcases\test_login.py", line 44, in test_login
    self.assertDictIn(expected,res)
  File "C:\project\python_35\py35_21day_project\testcases\test_login.py", line 60, in assertDictIn
    raise AssertionError("{} not in {}".format(expected, res))
AssertionError: {'code': 2, 'msg': '无效的手机格式'} not in {'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2020-12-19 11:45:28,685 - [test_login.py-->line:52] - INFO: 用例--【登录成功】---执行通过
2020-12-19 11:45:28,750 - [test_login.py-->line:52] - INFO: 用例--【手机号为空】---执行通过
2020-12-19 11:45:28,800 - [test_login.py-->line:52] - INFO: 用例--【密码为空】---执行通过
2020-12-19 11:45:28,863 - [test_login.py-->line:52] - INFO: 用例--【手机号未注册】---执行通过
2020-12-19 11:45:28,935 - [test_login.py-->line:52] - INFO: 用例--【密码错误】---执行通过
2020-12-19 11:45:28,998 - [test_login.py-->line:52] - INFO: 用例--【手机号格式错误】---执行通过
